version: '3.1'

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: telecurso_2022_net_marcio_db
    ports:
      - 5432:5432
    networks:
      - telecurso_2022_net_marcio_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - database
    ports:
      - "5050:80"
    networks:
      - telecurso_2022_net_marcio_network

networks:
  telecurso_2022_net_marcio_network:
    name: telecurso_2022_net_marcio_network
    driver: bridge
