version: '3.8'

services:
  # prd-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: production
  #   volumes:
  #     - .:/app
  #   command: npm run start
  #   ports:
  #     - 8081:8080
  #   environment:
  #     NODE_ENV: production
  #     DEBUG: "*"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      DEBUG: "*"
